name: pokedex
description: Flutter Implementation of PokeDex.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  flutter_screenutil: ^0.5.3
  bubble_tab_indicator: ^0.1.4
  percent_indicator: ^2.1.1
  cached_network_image: ^1.1.1
  simple_animations: ^1.3.3
  sprung: ^1.1.0+11

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0
  flutter_launcher_icons: ^0.7.2+1
  test: ^1.6.3

flutter:
  assets:
    - assets/img/tag/
    - assets/img/type/
    - assets/img/gender_ring.png
    - assets/img/capture_pokeball.png
    - assets/img/arrow.png
    - assets/img/pokeball_loading.gif
    - assets/img/pokeball_img_load.png
    - assets/img/pokeball2.png
    - assets/launcher/foreground.png
    - assets/img/pokemon_logo.png
    - assets/img/ash.png
    - assets/img/ball.png
    - assets/img/pokeball.png
    - assets/img/pokeball3.png
    - assets/img/pokeshake.gif

  uses-material-design: true

fonts:
      - family: Avenir-Book
      - asset: assets/fonts/Avenir-Book.ttc
      - family: Avenir-Heavy
      - asset: assets/fonts/Avenir-Heavy.ttc
      - family: Avenir-Medium
      - asset: assets/fonts/Avenir-Medium.ttc
      - family: Pokemon Solid
      - asset: assets/fonts/PokemonSolid.ttf
      - family: Pokemon Hollow
      - asset: assets/fonts/PokemonHollow.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/foreground.png"
  image_path_android: "assets/launcher/foreground.png"
  adaptive_icon_background: "assets/launcher/foreground.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"